##############################################################################
# CtrlSysV2 Minimal Constraints
#
# External interfaces expected at the top level:
#   - DDR        : Zynq PS DDR interface, handled by the Processing System / BD
#   - FIXED_IO   : Zynq PS MIO interface, handled by the Processing System / BD
#   - i2c_scl_0    : PL I2C SCL pin
#   - i2c_sda_0    : PL I2C SDA pin
#
# This file intentionally removes old ADC, DAC, SPI, LED, and expansion-header
# constraints that are no longer external interfaces in the current design.
#
# Pin choice:
#   Uses the same physical pins as the old working IIC_0 bus:
#     IIC_0_scl_io -> G17
#     IIC_0_sda_io -> H16
##############################################################################

# ----------------------------------------------------------------------------
# PL I2C bus
# ----------------------------------------------------------------------------
# These names must match the top-level port names generated by your Vivado
# wrapper. If your BD external interface is named IIC_0 instead, rename these
# get_ports targets to IIC_0_scl_io and IIC_0_sda_io.
# ----------------------------------------------------------------------------

set_property PACKAGE_PIN G17 [get_ports {i2c_scl_0}]
set_property PACKAGE_PIN H16 [get_ports {i2c_sda_0}]

set_property IOSTANDARD LVCMOS33 [get_ports {i2c_scl_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_sda_0}]

# I2C is open-drain/open-collector style, so the lines need pull-ups.
# External pull-ups are preferred for real hardware. These internal pull-ups are
# useful as a fallback and match the style of the previous working constraints.
set_property PULLUP true [get_ports {i2c_scl_0}]
set_property PULLUP true [get_ports {i2c_sda_0}]

# Conservative edge/drive settings for low-speed I2C-style GPIO.
set_property SLEW SLOW [get_ports {i2c_scl_0}]
set_property SLEW SLOW [get_ports {i2c_sda_0}]
set_property DRIVE 4 [get_ports {i2c_scl_0}]
set_property DRIVE 4 [get_ports {i2c_sda_0}]
