# Generate and add project-level constraints for ctrlsys_core.
# This script locates paths relative to itself, so it does not depend on Vivado's cwd.

set script_dir [file normalize [file dirname [info script]]]
set source_dir [file normalize [file join $script_dir ".."]]
set repo_root  [file normalize [file join $source_dir ".."]]
set config_path [file normalize [file join $source_dir "config" "system_config.json"]]
set xdc_dir    [file normalize [file join $repo_root "source" "constraints"]]
set xdc_path   [file normalize [file join $xdc_dir "ctrlsys_core_generated.xdc"]]

proc read_text_file { path } {
    set fp [open $path "r"]
    set text [read $fp]
    close $fp
    return $text
}

proc json_get_int { json_text key default_value } {
    set pattern [format {\"%s\"\s*:\s*([0-9]+)} $key]
    if {[regexp $pattern $json_text -> value]} {
        return $value
    }
    return $default_value
}

proc json_get_string { json_text key default_value } {
    set pattern [format {\"%s\"\s*:\s*\"([^\"]*)\"} $key]
    if {[regexp $pattern $json_text -> value]} {
        return $value
    }
    return $default_value
}

proc detect_bus_port_base { candidates default_base } {
    foreach base $candidates {
        if {[llength [get_ports -quiet "${base}\[*\]"]] > 0} {
            return $base
        }
    }
    return $default_base
}

set top_module_name "design_1"
set num_sensors ""
set num_sensors_source ""

set core [get_bd_cells -quiet *ctrlsys_core*]
if {[llength $core] == 1} {
    set num_sensors [get_property CONFIG.NUM_SENSORS $core]
    set num_sensors_source "Block Design cell $core"
}

if {$num_sensors eq ""} {
    if {![file exists $config_path]} {
        error "Could not derive NUM_SENSORS from the open Block Design and missing fallback config: $config_path"
    }

    set config_text [read_text_file $config_path]
    set top_module_name [json_get_string $config_text "TOP_MODULE_NAME" "design_1"]
    set num_sensors [json_get_int $config_text "NUM_SENSORS" 1]
    set num_sensors_source $config_path
}

if {$num_sensors < 1 || $num_sensors > 6} {
    error "NUM_SENSORS must be in the range 1..6; got $num_sensors from $num_sensors_source"
}

# Red Pitaya STEMLab-14 expansion connector rows.
# Sensor i uses row i: DIOi_N for SDA and DIOi_P for SCL.
set dio_p_pins [list G17 H16 J18 K17 L14 L16]
set dio_n_pins [list G18 H17 H18 K18 L15 L17]
set sda_port_base [detect_bus_port_base [list sda_0 sda] sda_0]
set scl_port_base [detect_bus_port_base [list scl_0 scl] scl_0]

file mkdir $xdc_dir

set fp [open $xdc_path "w"]

puts $fp "# Auto-generated constraints for ctrlsys_core"
puts $fp "# Generated by: [file normalize [info script]]"
puts $fp "# Config: $config_path"
puts $fp "# TOP_MODULE_NAME: $top_module_name"
puts $fp "# NUM_SENSORS: $num_sensors"
puts $fp "# NUM_SENSORS source: $num_sensors_source"
puts $fp "# SDA port base: $sda_port_base"
puts $fp "# SCL port base: $scl_port_base"
puts $fp ""
puts $fp "# Keep these constraints at the project level because package pins are board-specific."
puts $fp "# Mapping: sensor i -> SDA on DIOi_N, SCL on DIOi_P."
puts $fp ""
puts $fp "# Sensor pin constraints"
for {set i 0} {$i < $num_sensors} {incr i} {
    set sda_pin [lindex $dio_n_pins $i]
    set scl_pin [lindex $dio_p_pins $i]
    set sda_port [format {%s[%d]} $sda_port_base $i]
    set scl_port [format {%s[%d]} $scl_port_base $i]
    puts $fp ""
    puts $fp "# Sensor $i: DIO${i}_N/DIO${i}_P"
    puts $fp [format {set_property PACKAGE_PIN %s [get_ports {%s}]} $sda_pin $sda_port]
    puts $fp [format {set_property IOSTANDARD LVCMOS33 [get_ports {%s}]} $sda_port]
    puts $fp [format {set_property PULLUP true [get_ports {%s}]} $sda_port]
    puts $fp [format {set_property SLEW SLOW [get_ports {%s}]} $sda_port]
    puts $fp [format {set_property DRIVE 4 [get_ports {%s}]} $sda_port]
    puts $fp [format {set_property PACKAGE_PIN %s [get_ports {%s}]} $scl_pin $scl_port]
    puts $fp [format {set_property IOSTANDARD LVCMOS33 [get_ports {%s}]} $scl_port]
    puts $fp [format {set_property PULLUP true [get_ports {%s}]} $scl_port]
    puts $fp [format {set_property SLEW SLOW [get_ports {%s}]} $scl_port]
    puts $fp [format {set_property DRIVE 4 [get_ports {%s}]} $scl_port]
}

close $fp

set constrs [get_filesets -quiet constrs_1]
if {[llength $constrs] == 0} {
    create_fileset -constrset constrs_1
    set constrs [get_filesets constrs_1]
}

if {[llength [get_files -quiet $xdc_path]] == 0} {
    add_files -fileset $constrs $xdc_path
}

puts "Generated constraints: $xdc_path"
