import config_pkg::*;

module top(
    input logic clk,
    input logic rst,

    inout wire [NUM_SENSORS-1:0] sda,
    inout wire [NUM_SENSORS-1:0] scl,

    output logic       axi_iic_sda_i,
    input  logic       axi_iic_sda_o,
    input  logic       axi_iic_sda_t,
    output logic       axi_iic_scl_i,
    input  logic       axi_iic_scl_o,
    input  logic       axi_iic_scl_t,

    input  logic        s_axi_lite_awvalid,
    output logic        s_axi_lite_awready,
    input  logic [9:0]  s_axi_lite_awaddr,
    input  logic        s_axi_lite_wvalid,
    output logic        s_axi_lite_wready,
    input  logic [31:0] s_axi_lite_wdata,
    output logic [1:0]  s_axi_lite_bresp,
    output logic        s_axi_lite_bvalid,
    input  logic        s_axi_lite_bready,
    input  logic        s_axi_lite_arvalid,
    output logic        s_axi_lite_arready,
    input  logic [9:0]  s_axi_lite_araddr,
    output logic        s_axi_lite_rvalid,
    input  logic        s_axi_lite_rready,
    output logic [31:0] s_axi_lite_rdata,
    output logic [1:0]  s_axi_lite_rresp,

    output logic [31:0] m_axi_s2mm_awaddr,
    output logic [7:0]  m_axi_s2mm_awlen,
    output logic [2:0]  m_axi_s2mm_awsize,
    output logic [1:0]  m_axi_s2mm_awburst,
    output logic [2:0]  m_axi_s2mm_awprot,
    output logic [3:0]  m_axi_s2mm_awcache,
    output logic        m_axi_s2mm_awvalid,
    input  logic        m_axi_s2mm_awready,
    output logic [31:0] m_axi_s2mm_wdata,
    output logic [3:0]  m_axi_s2mm_wstrb,
    output logic        m_axi_s2mm_wlast,
    output logic        m_axi_s2mm_wvalid,
    input  logic        m_axi_s2mm_wready,
    input  logic [1:0]  m_axi_s2mm_bresp,
    input  logic        m_axi_s2mm_bvalid,
    output logic        m_axi_s2mm_bready,

    output logic        s2mm_prmry_reset_out_n,
    output logic        s2mm_introut,
    output logic [31:0] axi_dma_tstvec
);

logic        axis_tvalid;
logic        axis_tready;
logic [31:0] axis_tdata;
logic [3:0]  axis_tkeep;
logic        axis_tlast;

ctrlsys_core u_ctrlsys_core (
    .clk(clk),
    .rst(rst),
    .sda(sda),
    .scl(scl),
    .m_axis_tvalid(axis_tvalid),
    .m_axis_tready(axis_tready),
    .m_axis_tdata(axis_tdata),
    .m_axis_tkeep(axis_tkeep),
    .m_axis_tlast(axis_tlast),
    .s00_axi_aclk(clk),
    .s00_axi_aresetn(~rst),
    .s00_axi_awaddr(6'b0),
    .s00_axi_awprot(3'b0),
    .s00_axi_awvalid(1'b0),
    .s00_axi_awready(),
    .s00_axi_wdata(32'b0),
    .s00_axi_wstrb(4'hF),
    .s00_axi_wvalid(1'b0),
    .s00_axi_wready(),
    .s00_axi_bresp(),
    .s00_axi_bvalid(),
    .s00_axi_bready(1'b1),
    .s00_axi_araddr(6'b0),
    .s00_axi_arprot(3'b0),
    .s00_axi_arvalid(1'b0),
    .s00_axi_arready(),
    .s00_axi_rdata(),
    .s00_axi_rresp(),
    .s00_axi_rvalid(),
    .s00_axi_rready(1'b1),
    .axi_iic_sda_i(axi_iic_sda_i),
    .axi_iic_sda_o(axi_iic_sda_o),
    .axi_iic_sda_t(axi_iic_sda_t),
    .axi_iic_scl_i(axi_iic_scl_i),
    .axi_iic_scl_o(axi_iic_scl_o),
    .axi_iic_scl_t(axi_iic_scl_t)
);

axi_dma_0 u_axi_dma_0 (
    .s_axi_lite_aclk(clk),
    .m_axi_s2mm_aclk(clk),
    .axi_resetn(~rst),

    .s_axi_lite_awvalid(s_axi_lite_awvalid),
    .s_axi_lite_awready(s_axi_lite_awready),
    .s_axi_lite_awaddr(s_axi_lite_awaddr),
    .s_axi_lite_wvalid(s_axi_lite_wvalid),
    .s_axi_lite_wready(s_axi_lite_wready),
    .s_axi_lite_wdata(s_axi_lite_wdata),
    .s_axi_lite_bresp(s_axi_lite_bresp),
    .s_axi_lite_bvalid(s_axi_lite_bvalid),
    .s_axi_lite_bready(s_axi_lite_bready),
    .s_axi_lite_arvalid(s_axi_lite_arvalid),
    .s_axi_lite_arready(s_axi_lite_arready),
    .s_axi_lite_araddr(s_axi_lite_araddr),
    .s_axi_lite_rvalid(s_axi_lite_rvalid),
    .s_axi_lite_rready(s_axi_lite_rready),
    .s_axi_lite_rdata(s_axi_lite_rdata),
    .s_axi_lite_rresp(s_axi_lite_rresp),

    .m_axi_s2mm_awaddr(m_axi_s2mm_awaddr),
    .m_axi_s2mm_awlen(m_axi_s2mm_awlen),
    .m_axi_s2mm_awsize(m_axi_s2mm_awsize),
    .m_axi_s2mm_awburst(m_axi_s2mm_awburst),
    .m_axi_s2mm_awprot(m_axi_s2mm_awprot),
    .m_axi_s2mm_awcache(m_axi_s2mm_awcache),
    .m_axi_s2mm_awvalid(m_axi_s2mm_awvalid),
    .m_axi_s2mm_awready(m_axi_s2mm_awready),
    .m_axi_s2mm_wdata(m_axi_s2mm_wdata),
    .m_axi_s2mm_wstrb(m_axi_s2mm_wstrb),
    .m_axi_s2mm_wlast(m_axi_s2mm_wlast),
    .m_axi_s2mm_wvalid(m_axi_s2mm_wvalid),
    .m_axi_s2mm_wready(m_axi_s2mm_wready),
    .m_axi_s2mm_bresp(m_axi_s2mm_bresp),
    .m_axi_s2mm_bvalid(m_axi_s2mm_bvalid),
    .m_axi_s2mm_bready(m_axi_s2mm_bready),

    .s2mm_prmry_reset_out_n(s2mm_prmry_reset_out_n),
    .s_axis_s2mm_tdata(axis_tdata),
    .s_axis_s2mm_tkeep(axis_tkeep),
    .s_axis_s2mm_tvalid(axis_tvalid),
    .s_axis_s2mm_tready(axis_tready),
    .s_axis_s2mm_tlast(axis_tlast),
    .s2mm_introut(s2mm_introut),
    .axi_dma_tstvec(axi_dma_tstvec)
);

endmodule
